name       : python3-guessit
version    : 2.1.0
release    : 3
source     :
    - https://pypi.python.org/packages/31/bc/caa1a21ceab5b72cefd438937eac7ff72514b4e15c74e83b63765b688481/guessit-2.1.0.tar.gz : a534a46bef3bbac7b313a55744860a9ddd5b7fae6abb6f6ae8bbace2b3e973b1
license    : LGPL-3.0
component  : programming.python
summary    : a library for guessing information from video filenames.
description: |
    a library for guessing information from video filenames.
builddeps  :
    - pkgconfig(python3)
    - pytest-runner
build      : |
    %python3_setup
install    : |
    %python3_install
